// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPWeBaYJeYhUNUNXnaV9HaIlJgTjByiMQ',
    appId: '1:1093715874564:web:42ce109d9de475a2fa3651',
    messagingSenderId: '1093715874564',
    projectId: 'u-seat-manag',
    authDomain: 'u-seat-manag.firebaseapp.com',
    storageBucket: 'u-seat-manag.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPyRfGdeXH5dfyxPlnOgYZzJZNIkl17GQ',
    appId: '1:1093715874564:android:3786451be21717d8fa3651',
    messagingSenderId: '1093715874564',
    projectId: 'u-seat-manag',
    storageBucket: 'u-seat-manag.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJxU3oe2P2oIuNq_s1tpeEw78nghL4HyU',
    appId: '1:1093715874564:ios:9815bfe9c4700ec7fa3651',
    messagingSenderId: '1093715874564',
    projectId: 'u-seat-manag',
    storageBucket: 'u-seat-manag.appspot.com',
    iosBundleId: 'com.example.seatManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJxU3oe2P2oIuNq_s1tpeEw78nghL4HyU',
    appId: '1:1093715874564:ios:9815bfe9c4700ec7fa3651',
    messagingSenderId: '1093715874564',
    projectId: 'u-seat-manag',
    storageBucket: 'u-seat-manag.appspot.com',
    iosBundleId: 'com.example.seatManagement',
  );
}
